default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: testing
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: myapp_production
